apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000  # Expose backend service on port 5000
      targetPort: 5000  # The port the container is listening on
      nodePort: 30002  # Port exposed on the local machine (can change this)
  type: NodePort  # Expose the service via NodePort for local access
